language: c
addons:
    apt:
        config:
            retries: true
        packages:
            - valgrind
matrix:
    include:
        - os: linux
          compiler: gcc
          dist: trusty
        - os: linux
          compiler: gcc
          dist: xenial
script:
    - |
        set -eo pipefail
        make
branches:
    only:
        - master

notifications:
  email: false
